[versions]
kotlin = "1.8.20"
gradle-plugin-publish = "1.2.1"
mybatisflex = "1.8.7"
mybatisflex-kotlin-extensions = "1.0.9"
mybatisflex-kotlin-plugin = "1.0.1"
mybatisflex-kotlin-ksp = "1.0.1"
mybatisflex-kotlin-codegen = "1.0.0"
junit-jupiter = "5.8.1"
mysql = "8.0.33"
h2 = "2.1.214"
spring = "5.3.27"
ksp-api = "1.8.20-1.0.11"
kotlinpoet = "1.12.0"
dokka = "1.8.20"
noarg = "1.8.20"
allopen = "1.8.20"

[libraries]
mybatisflex-core = { group = "com.mybatis-flex", name = "mybatis-flex-core", version.ref = "mybatisflex" }
mybatisflex-spring = { group = "com.mybatis-flex", name = "mybatis-flex-spring", version.ref = "mybatisflex" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
spring-test = { group = "org.springframework", name = "spring-test", version.ref = "spring" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp-api" }
mybatisflex-annotation = { group = "com.mybatis-flex", name = "mybatis-flex-annotation", version.ref = "mybatisflex" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
mybatisflex-codegen = { group = "com.mybatis-flex", name = "mybatis-flex-codegen", version.ref = "mybatisflex" }
dokka = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-api" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "noarg" }
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "allopen" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
com-mybatis-flex-kotlin = { id = "com.mybatis-flex.kotlin", version.ref = "mybatisflex-kotlin-plugin" }
[bundles]
